package middleware

import (
	"fmt"
	"strings"

	"equipflow-backend/internal/config"
	"equipflow-backend/internal/domain"

	"github.com/gofiber/fiber/v2"
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

// SupabaseClaims represents the JWT payload generated by Supabase Auth
type SupabaseClaims struct {
	Sub   string                 `json:"sub"`   // Supabase auth user UUID
	Email string                 `json:"email"` // User email
	Role  string                 `json:"role"`  // default: authenticated
	AppMetadata map[string]interface{} `json:"app_metadata"`
	UserMetadata map[string]interface{} `json:"user_metadata"`
	jwt.RegisteredClaims
}

// AuthMiddleware verifies the Supabase JWT token and sets ContextUser in c.Locals
func AuthMiddleware(cfg *config.Config, db *gorm.DB) fiber.Handler {
	return func(c *fiber.Ctx) error {
		// ---------------------------------------------------------------------
		// DEV / TEST MODE: Support X-Dev-Role for rapid testing in development
		// ---------------------------------------------------------------------
		if cfg.Env == "development" {
			devRole := c.Get("X-Dev-Role")
			if devRole != "" {
				// Check if there is an existing profile in DB with this role
				var profile domain.Profile
				if err := db.WithContext(c.Context()).Where("role = ? AND is_active = true", devRole).First(&profile).Error; err == nil {
					c.Locals("user", domain.ContextUser{
						ID:    profile.ID,
						Email: profile.Email,
						Role:  profile.Role,
					})
					return c.Next()
				}

				// If not found in DB, auto-create a persistent dev profile so foreign keys succeed!
				mockDevID := uuid.New()
				newDevProfile := domain.Profile{
					ID:       mockDevID,
					Email:    fmt.Sprintf("dev-%s@equipflow.local", strings.ToLower(devRole)),
					FullName: fmt.Sprintf("Dev %s", devRole),
					Role:     domain.UserRole(devRole),
					IsActive: true,
				}
				_ = db.WithContext(c.Context()).Create(&newDevProfile).Error

				c.Locals("user", domain.ContextUser{
					ID:    newDevProfile.ID,
					Email: newDevProfile.Email,
					Role:  newDevProfile.Role,
				})
				return c.Next()
			}
		}

		authHeader := c.Get("Authorization")
		if authHeader == "" {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"error": "Missing Authorization header",
			})
		}

		parts := strings.Split(authHeader, " ")
		if len(parts) != 2 || parts[0] != "Bearer" {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"error": "Invalid Authorization header format. Expected 'Bearer <token>'",
			})
		}

		tokenString := parts[1]

		// Parse and validate token
		token, err := jwt.ParseWithClaims(tokenString, &SupabaseClaims{}, func(token *jwt.Token) (interface{}, error) {
			// Supabase uses HS256 with project JWT Secret
			if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
				return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
			}
			return []byte(cfg.SupabaseJWTSecret), nil
		})

		if err != nil || !token.Valid {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"error": "Invalid or expired JWT token",
			})
		}

		claims, ok := token.Claims.(*SupabaseClaims)
		if !ok {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"error": "Could not parse JWT claims",
			})
		}

		userUUID, err := uuid.Parse(claims.Sub)
		if err != nil {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"error": "Invalid user ID format in token",
			})
		}

		// Query user profile from database to get the latest authoritative Role & status
		var profile domain.Profile
		if err := db.WithContext(c.Context()).Where("id = ? AND is_active = true", userUUID).First(&profile).Error; err != nil {
			if err == gorm.ErrRecordNotFound {
				return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
					"error": "User profile not found or account is deactivated",
				})
			}
			return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
				"error": "Failed to retrieve user profile",
			})
		}

		// Store authenticated user in fiber.Ctx.Locals
		contextUser := domain.ContextUser{
			ID:    profile.ID,
			Email: profile.Email,
			Role:  profile.Role,
		}
		c.Locals("user", contextUser)

		return c.Next()
	}
}

// GetUserFromContext is a helper to retrieve authenticated user from fiber.Ctx
func GetUserFromContext(c *fiber.Ctx) (*domain.ContextUser, error) {
	u := c.Locals("user")
	if u == nil {
		return nil, fmt.Errorf("user context not found")
	}
	user, ok := u.(domain.ContextUser)
	if !ok {
		return nil, fmt.Errorf("invalid user context type")
	}
	return &user, nil
}
